### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by cbezrouk** [jjsouthworth/GTOCX#2]
This issue can be used to keep track of our high priority tasks. To claim a task, click and drag it into your task list. Feel free to add to this list.

# Top Priority Tasks
- [ ] Add code to populate a ShipLog object once the "zombie brain" has made a decision about the destination.
- [ ] Integrate the "zombie brain" with the event processor to create our first working simulation.

## Secondary Priority Tasks
- [ ] Code a solution file reader and use it on provided solution files to verify the merit function is working properly.
- [ ] Serialize our simulation data structure (and/or create a solution file writer?).

### Dan's Tasks
- [x] Write a function that produces an optimal two-impulse transfer between two stars where the arrival time is allowed to vary but should probably be bounded. Placeholder available in the SettlerShipTransfer class (transfer.cpp).
### Kyle's Tasks
- [ ] Code the merit function based on a vector of ShipLog objects.
- [ ] Add member functions to the ShipLog class that will make computing the merit function easier.

### Collin's Tasks
- [ ] Add a dense-output propagation function to propagate.cpp for assessing en-route proximity to stars (mother ship) and for animating our solutions.
